//@version=6
indicator("p6", overlay=true, max_boxes_count=500)
type swp_boxBr
    box swp_bx
    bool br
    int dr
swp_extend = input.bool(true, 'Extend')
var array<swp_boxBr> swp_aBoxBr = array.new<swp_boxBr>(1, swp_boxBr.new())
if bar_index == 10
    swp_aBoxBr.unshift(swp_boxBr.new(box.new(bar_index-1, high, bar_index+1, low), false, 1))
if swp_extend
    for swp_bxi = 0 to swp_aBoxBr.size() - 1
        swp_bxr = swp_aBoxBr.get(swp_bxi)
        if not na(swp_bxr.swp_bx)
            swp_bxr.swp_bx.set_right(bar_index)
plot(close, "c")
