#!/usr/bin/env python3
"""lqz_vision_build.py — DELIVERABLE 3: plutus-vision-v1.pine.

  = the operator's candle liquidity (the DETECTOR that won the split, from lqz-plutus)
  + the LuxAlgo SMC supply/demand zones, extracted VERBATIM from plutus-vision-v0.pine
  + the shared full-width LQZ display.

Architecture note: this extracts SECTIONS, not the whole v0 body. D2 proves that
core+render on their own behave; concatenating all of v0 (D1) is what strands the
cluster — see DEBUG/FAILURE records.

  python3 scripts/lqz_vision_build.py [out.pine]
"""
import pathlib, re, sys

W = pathlib.Path(__file__).resolve().parent.parent
V0 = (W / "plutus-vision-v0.pine").read_text().split("\n")
CORE = (W / "plutus-vision-lqz/lqz-core.pine").read_text()
RENDER = (W / "plutus-vision-lqz/lqz-render.pine").read_text()

STUBS = """lqzV1PoolMid()  => float(na)
lqzV1PoolRail() => 0.0
lqzV1SweepPrc() => float(na)
lqzV1VoidLo()   => float(na)
lqzV1VoidHi()   => float(na)"""


def section(name: str) -> str:
    """Return one `// ═══ NAME ═══` block verbatim from v0."""
    start = next(i for i, l in enumerate(V0) if l.startswith(f"// ═══ {name} ═══"))
    end = len(V0)
    for j in range(start + 1, len(V0)):
        if V0[j].startswith("// ═══ ") and V0[j].rstrip().endswith("═══"):
            end = j
            break
    return "\n".join(V0[start:end]).rstrip() + "\n"


def header() -> str:
    """v0's declarations the SMC block depends on (its own inputs + shared state)."""
    out, on = [], False
    for l in V0:
        if l.startswith("// ═══ SMC ═══"):
            break
        if re.match(r"^(indicator|var |type |[A-Za-z_][A-Za-z0-9_]*\s*=\s*input\.)", l.strip()):
            if l.strip().startswith("indicator("):
                continue
            out.append(l)
    return "\n".join(out)


def build() -> str:
    smc = section("SMC")
    # v0 declares the SMC inputs twice (once in the header group, once inside the block);
    # keep only what the block itself needs by dropping the pre-header declarations that
    # duplicate smc_-prefixed names.
    decls = header()
    keep = []
    for l in decls.split("\n"):
        m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=", l)
        if m and m.group(1).startswith(("smc_", "pv_")):
            continue
        keep.append(l)
    decls = "\n".join(keep)

    core_body = CORE[CORE.index("// ── inputs ──"):]
    # the winner is the candle detector; the LuxAlgo tap stays stubbed in D3
    core_body = core_body.replace(
        'lqzSource   = input.string("both"', 'lqzSource   = input.string("candles"', 1)

    return (
        "//@version=6\n"
        "// plutus-vision-v1 — the operator's candle liquidity + the LuxAlgo SMC S/D zones\n"
        "// GENERATED by scripts/lqz_vision_build.py — edit plutus-vision-lqz/*.pine, not this file.\n"
        'indicator("Plutus Vision v1", overlay = true)\n'
        f"{STUBS}\n\n"
        f"{decls}\n\n"
        "// ═════════════ SMC (verbatim from plutus-vision-v0.pine) ═════════════\n"
        f"{smc}\n\n"
        "// ═════════════ LQZ core + full-width render ═════════════\n"
        f"{core_body}\n\n{RENDER}\n"
        "if barstate.islast\n    f_lqzRender()\n"
    )


if __name__ == "__main__":
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else W / "plutus-vision-v1.pine"
    txt = build()
    out.write_text(txt)
    print(f"wrote {out.name}  {len(txt.splitlines())} lines")