#!/usr/bin/env python3
"""lqz_assemble.py — stitch CORE + RENDER + a host prelude into a deliverable .pine.

Pine v6 has no include mechanism, so the W1/W2 "interface" is a TEXT contract:
CORE declares the zone arrays, RENDER draws them, and each deliverable supplies
the five lqzV1* accessors plus its own detector wiring.

  python3 scripts/lqz_assemble.py <out.pine> --candles|--luxalgo|--both [--title T]
"""
import argparse, pathlib, re, sys

W = pathlib.Path(__file__).resolve().parent.parent
CORE = (W / "plutus-vision-lqz/lqz-core.pine").read_text()
RENDER = (W / "plutus-vision-lqz/lqz-render.pine").read_text()

PREAMBLE = """//@version=6
// {title}
// GENERATED by scripts/lqz_assemble.py — edit plutus-vision-lqz/*.pine, not this file.
indicator("{title}", overlay = true)
{accessors}
"""

STUB_ACCESSORS = """lqzV1PoolMid()  => float(na)
lqzV1PoolRail() => 0.0
lqzV1SweepPrc() => float(na)
lqzV1VoidLo()   => float(na)
lqzV1VoidHi()   => float(na)"""

TAIL = """
// ── emit on the last bar so the full history is in the arrays ────────────────
if barstate.islast
    f_lqzRender()
"""


def build(title: str, accessors: str, mode: str, source_override: str | None = None) -> str:
    core = CORE if source_override is None else re.sub(
        r'(lqzSource\s*=\s*input\.string)\("both"', r'\1("%s"' % source_override, CORE)
    assert 'input.string("candles"' in core or source_override is None
    return PREAMBLE.format(title=title, accessors=accessors) + core + RENDER + TAIL


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--candles", action="store_true")
    ap.add_argument("--luxalgo", action="store_true")
    ap.add_argument("--both", action="store_true")
    ap.add_argument("--title", default="LQZ")
    a = ap.parse_args()
    if a.candles:
        txt = build(a.title, STUB_ACCESSORS, "candles", "candles")
    elif a.luxalgo or a.both:
        txt = build(a.title, STUB_ACCESSORS, "luxalgo" if a.luxalgo else "both")
    else:
        sys.exit("choose --candles | --luxalgo | --both")
    pathlib.Path(a.out).write_text(txt)
    print(f"wrote {a.out}  {len(txt.splitlines())} lines")
