#!/usr/bin/env python3
"""gen_canon.py — (re)write the 11 canon docs in <tree>/context_management from the tree's
measured state. Hand-written state/rulings live in this file; every inventory (anchors, shas,
inputs, ViL cases, parity) is GENERATED from disk at run time so it cannot drift.
  python3 scripts/gen_canon.py
"""
import hashlib, json, pathlib, re, time

W = pathlib.Path(__file__).resolve().parent.parent
C = W / "context_management"; C.mkdir(exist_ok=True)
NOW = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
PINE = W / "plutus-vision-v0.pine"
SRC = W / "sources"


def sha(p, n=64):
    return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()[:n]


def lines(p):
    return sum(1 for _ in open(p, "rb"))


PSHA = sha(PINE)
TXT = PINE.read_text().split("\n")
SECTIONS = [(i + 1, re.search(r"═══ (\w+)", l).group(1)) for i, l in enumerate(TXT) if "═══" in l and l.startswith("// ═══")]


def section_of(n):
    s = "HEADER"
    for ln, name in SECTIONS:
        if n >= ln:
            s = name
    return s


FUNCS = [(i + 1, l.split("=>")[0].strip()) for i, l in enumerate(TXT)
         if re.match(r"^(method )?[A-Za-z_][A-Za-z0-9_]*\(.*\)\s*=>", l)]
TYPES = [(i + 1, l.strip()) for i, l in enumerate(TXT) if l.startswith("type ")]
INPUTS = []
for i, l in enumerate(TXT):
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?:\d+\s*/\s*)?input\.(\w+)\s*\(\s*([^,]+),\s*(?:title\s*=\s*)?('[^']*'|\"[^\"]*\")?", l)
    if m:
        g = re.search(r"group\s*=\s*([A-Za-z_'\" ]+?)[,)]", l)
        INPUTS.append((i + 1, m.group(1), m.group(2), m.group(3).strip(), (m.group(4) or "''").strip("'\""),
                       (g.group(1).strip() if g else "-")))

VIL = json.loads((W / "vil/vil-results.json").read_text()) if (W / "vil/vil-results.json").exists() else {"scenarios": []}
CMP = json.loads((W / "COMPARE.json").read_text()) if (W / "COMPARE.json").exists() else {}

KEYFILES = ["plutus-vision-v0.pine", "scripts/pv-ide.sh", "scripts/pv-load.mjs", "scripts/pv-server.py",
            "scripts/vil.py", "scripts/compare.py", "scripts/gen_canon.py", "scripts/deguard.py",
            "pine-ide/ide/renderer/pine.html", "pine-ide/ide/renderer/tabs/_shell.js",
            "pine-ide/ide/renderer/tabs/pineshell.js", "pine-ide/ide/renderer/tabs/pineshell.css",
            "pine-ide/pine-ide/pine-ide.mjs", "pine-ide/pine-ide/vision.mjs", "pine-ide/pine-ide/gate.mjs",
            "pine-ide/pine-ide/pine-editor.mjs", "pine-ide/pine-ide/vil-rail.mjs",
            "pine-ide/pine-station/server.mjs", "pine-ide/pine-station/lib/run.mjs",
            "pine-ide/pine-station/lib/bars.mjs", "pine-ide/charts/workbench.js",
            "pine-ide/charts/workbench.bundle.js", "fixtures/bars/2026-07-06.json"]


def inv_rows(paths):
    out = ["| file | lines | sha256-16 |", "|---|---|---|"]
    for f in paths:
        p = W / f
        if p.exists() and p.is_file():
            out.append(f"| `{f}` | {lines(p)} | `{sha(p, 16)}` |")
        else:
            out.append(f"| `{f}` | ABSENT | — |")
    return out


HEAD = lambda title, purpose: [f"# {title}", "", f"_Generated by `scripts/gen_canon.py` at {NOW} · indicator sha256 `{PSHA}`._",
                               f"_Purpose: {purpose}_", ""]

docs = {}

# ───────────────────────────────── 1. POST-COMPACTION_PROMPT
d = HEAD("POST-COMPACTION PROMPT — PLUTUS VISION", "what a fresh agent reads FIRST to resume with zero loss.")
d += ["## THE MISSION (operator's words)", "",
      "> \"take the working 4 lux algo indicators, bundle them into ONE indicator, and render it on the pine IDE chart",
      "> so i can see everything and MAKE SURE IT IS PROPERLY FUCKING DONE.\"",
      "> \"now we need to properly optimzie and fine tune this.\" (2026-10-01, after the v1 baseline)", "",
      "## THE STATE IN ONE SCREEN", "",
      f"- v1 CLEAN BASELINE sealed at `Checkpoints/v1-clean-baseline/` (self-contained: indicator + IDE + launcher + fixture).",
      f"- Indicator `plutus-vision-v0.pine` sha256 `{PSHA}` ({len(TXT)} lines).",
      "- Parity vs the 4 sources: SMC 195/195 · POOLS 25/25 · SWEEPS 258/258 (section-alone) · VOIDS newest 380/500.",
      "- ViL ship gate `scripts/vil.py`: VIL GATE PASS on 15m/30m/1H/4H; engineer read FAIL with 3 open deltas.",
      "- Open tuning: non-interactable drawings · sub-1H visuals · LuxAlgo settings map · settings menu under the asset name · D timeframe.",
      "",
      "## READ IN THIS ORDER (absolute paths)", "",
      f"1. `{C}/CURRENT_STATE.md` — every module, every anchor, every port.",
      f"2. `{C}/NEXT_STEPS.md` — the tuning plan with owner files.",
      f"3. `{C}/DECISION_CHAIN.md` — the operator's rulings verbatim (they override everything).",
      f"4. `{C}/EVIDENCE_STATE.md` — what is proven, by which run, with which sha.",
      f"5. `{W}/DEBUG_LOG.md` — EN-001..EN-021: every trap already paid for.",
      f"6. `{W}/TESTING_LOG.md` — plan P-01..P-06 + results R-01..R-04.",
      f"7. `/home/leviathan/JARVIS_WORKSPACE/Shared_Workspace/Bibles/VISION_IN_THE_LOOP_ENGINEERING_BIBLE.md` — the ship-gate law.",
      "",
      "## THE FIRST FIVE COMMANDS", "", "```",
      "pine-ide                                   # IDE on display :3 with the indicator loaded + RUN (9 s)",
      "pine-ide --shot /tmp/now.png               # then READ /tmp/now.png (vision in the loop)",
      f"python3 {W}/scripts/vil.py                 # ship gate: VIL GATE PASS expected",
      f"python3 {W}/scripts/compare.py             # parity: SMC 195/195 · POOLS 25/25 expected",
      f"PINE_IDE_HOME={W}/Checkpoints/v1-clean-baseline pine-ide   # run the sealed baseline instead",
      "```", "",
      "## THE LAWS THAT COST HOURS (never re-derive)", "",
      "1. `pine.html` must not call `mount()` — `_shell.js` auto-mounts; a second mount = two editors + the prefill chart.",
      "2. `pine.html` needs the html/body 100vh flex chain or the Vela canvas grows to ~24,000 px and reads blank.",
      "3. Editor API is `setSource/getSource/flush` — `setValue` does not exist and fails silently.",
      "4. Timeframe labels are `15m 30m 1H 4H` (uppercase H).",
      "5. Kill Chrome with pgrep + kill -9 and assert none survive — a survivor runs stale modules.",
      "6. The fork's rail is :9754; :9444/:9441/:9430 belong to the dashboard session — never touch them.",
      "7. Vela `pricelabel` prints the PRICE; Pine labels map to Vela `text`.",
      "8. One Pine script = one 500-box ceiling; VOIDS is bounded at 380 so SMC's bar-0 boxes survive.",
      "9. Every 'it works' needs the written expectation + independent reader + engineer read (ViL bible).",
      "10. The operator's words are the spec: no customising the LuxAlgo logic; simplest path; look at the images.",
      "", "## WHAT NOT TO DO", "",
      "- Do not add budget allocators, guards, or 'improvements' to the LuxAlgo logic (F-06).",
      "- Do not report a reader PASS as visual correctness without the engineer read (T-03, T-07).",
      "- Do not run the qwen code audit for this project — replaced by the ViL gate (F-05).",
      "- Do not edit the sealed checkpoint; work in the live tree, re-seal as v2.",
      ""]
docs["POST-COMPACTION_PROMPT"] = d

# ───────────────────────────────── 2. CURRENT_STATE
d = HEAD("CURRENT STATE — PLUTUS VISION", "the system as it is NOW: modules, anchors, ports, the settings surface.")
d += ["## 2.1 Topology", "", "```",
      "operator ── pine-ide ─► scripts/pv-ide.sh (W = own tree; relocatable)",
      "   :9741 station   pine-ide/pine-station/server.mjs   PineTS 0.10.0, fixture from <tree>/fixtures",
      "   :9754 VIL rail  pine-ide/pine-ide/vil-rail.mjs     /station/run proxy · /vil/look → local VLM :4171",
      "   :9851 server    scripts/pv-server.py               static renderer root + /api/v1/chart/bars",
      "   :9222 CDP       Chrome --app pine.html on X display :3 (software GL, profile /tmp/pv-ide-chrome)",
      "   pv-load.mjs ── CDP ─► window.PlutusPineShell.{editor.setSource, loadBars, run, chart, workbench}",
      "```", "",
      "## 2.2 Ports owned by this project (and the ones that are NOT)", "",
      "| port | owner | proof |", "|---|---|---|",
      "| 9741 | PLUTUS_VISION pine-station | `ss -ltnp` pid cwd = <tree>/pine-ide/pine-station |",
      "| 9754 | PLUTUS_VISION vil-rail | rail log `vil=<tree>/vil` |",
      "| 9851 | PLUTUS_VISION pv-server.py | `/api/v1/health` cells=12 |",
      "| 9222 | PLUTUS_VISION Chrome CDP | `/json/list` title `Plutus Vision — Pine IDE` |",
      "| 4171 | shared local VLM seat (Qwen3.5-4B) | reader id in vil-results.json |",
      "| 9430 9441 9444 9448 | PLUTUS/LIVE dashboard session — DO NOT TOUCH | process cwd under PLUTUS/LIVE/dashboard |",
      "",
      "## 2.3 The indicator — section map", "",
      "| section | first line | role |", "|---|---|---|",
      "| HEADER | 1 | provenance, measured parity, the one `indicator()` decl (line 15), merge-edit list |"]
roles = {"SMC": "Smart Money Concepts: structure (BOS/CHoCH), swings, order blocks, EQH/EQL, FVG, levels, zones",
         "SWEEPS": "Liquidity Sweeps: swing-pivot sweeps (wicks / outbreak+retest), sweep areas",
         "VOIDS": "Liquidity Voids (FVG): 13-slice void boxes, filled-void recolour; `voi_all` cap 380",
         "POOLS": "Buyside & Sellside Liquidity: zigzag pivots, liquidity zones + dotted lines, visible-levels pruning"}
for ln, name in SECTIONS:
    d.append(f"| {name} | {ln} | {roles.get(name, '')} |")
d += ["", "## 2.4 Every type (line anchor)", "", "| line | section | declaration |", "|---|---|---|"]
d += [f"| {ln} | {section_of(ln)} | `{t}` |" for ln, t in TYPES]
d += ["", "## 2.5 Every function / method (line anchor)", "", "| line | section | signature |", "|---|---|---|"]
d += [f"| {ln} | {section_of(ln)} | `{s[:90]}` |" for ln, s in FUNCS]
d += ["", "## 2.6 The settings surface — every input (line anchor)", "",
      f"{len(INPUTS)} inputs parsed (of {sum('input.' in l for l in TXT)} `input.` occurrences; the remainder are multi-line declarations).", "",
      "| line | section | var | kind | default | title | group |", "|---|---|---|---|---|---|---|"]
d += [f"| {ln} | {section_of(ln)} | `{v}` | {k} | `{dflt[:24]}` | {t[:34]} | {g[:22]} |" for ln, v, k, dflt, t, g in INPUTS]
d += ["", "## 2.7 IDE module status", "",
      "| module | status | anchor |", "|---|---|---|",
      "| standalone host | WORKING — single mount, height chain | `pine-ide/ide/renderer/pine.html` |",
      "| kernel | WORKING — run/loadBars/capture/look/runGate | `pine-ide/pine-ide/pine-ide.mjs` |",
      "| label mapping | WORKING — Pine label → Vela `text` | `pine-ide/pine-ide/vision.mjs:137` |",
      "| box border default | DEFECT OPEN — brass border on borderless source boxes (EN-021) | `pine-ide/pine-ide/vision.mjs` box block |",
      "| future anchors | WORKING — extrapolated ≤500 bars | `pine-ide/pine-station/lib/run.mjs:114-123` |",
      "| rail binding | WORKING — :9754 only | `pine-ide/pine-ide/gate.mjs:21` |",
      "| drawing interaction | DEFECT OPEN — drawings draggable | Vela drawing `locked` flag (workbench.bundle.js `_Drawing.locked`) |",
      "| indicator settings menu | ABSENT | — |",
      "| D timeframe | ABSENT — fixture has 15m/30m/1H/4H only | `fixtures/bars/2026-07-06.json` |",
      ""]
docs["CURRENT_STATE"] = d

# ───────────────────────────────── 3. NEXT_STEPS
d = HEAD("NEXT STEPS — PLUTUS VISION", "the queued tuning work, each with owner file, method and acceptance; the risk register.")
items = [
 ("N-1", "Drawings must not be interactable (operator item 1)",
  "Vela drawings carry `locked` (workbench.bundle.js `_Drawing` ctor `this.locked = false`). Set `locked: true` on every drawing vision.mjs adds (and/or mark them non-selectable).",
  "pine-ide/pine-ide/vision.mjs (`add()` spec)",
  "CDP: mousedown/mousemove/mouseup on a box → anchors unchanged; engineer read of a post-drag shot; vil.py PASS."),
 ("N-2", "VOIDS borders (EN-021, engineer delta D1)",
  "Source boxes with `border_color = na` must render borderless: vision.mjs box mapping must use transparent when borderColor is absent, never BRASS.",
  "pine-ide/pine-ide/vision.mjs (box block)",
  "15m/30m/4H shots show grey slices without tan stripes; vil.py PASS; engineer read D1 closed."),
 ("N-3", "Label overlap (D2) and right-edge clipping (D3)",
  "Honour the source label size (`size.tiny` for internal structure vs `small`) — pass Pine `size` through the station → vision `text.size`; for D3 check the right margin / scroll offset.",
  "pine-ide/pine-station/lib/run.mjs (label normalise) + vision.mjs (text size)",
  "Engineer read: no overlapping BOS/CHoCH at 15m right side; W/S visible."),
 ("N-4", "Sub-1H fine tuning (operator item 2)",
  "After N-2/N-3, re-read 15m/30m. Remaining clutter is SOURCE behaviour (LuxAlgo defaults); tuning = input values in the settings, NOT logic changes (DECISION D-07).",
  "settings (inputs) only; documented in docs/LUXALGO_SETTINGS_MAP.md",
  "Operator-visible 30m frame comparable to TradingView with the same inputs."),
 ("N-5", "LuxAlgo settings map (operator item 3)",
  "Write docs/LUXALGO_SETTINGS_MAP.md: per indicator — what it draws out of the box, every input (from CURRENT_STATE §2.6), the recommended setup per TF.",
  "docs/LUXALGO_SETTINGS_MAP.md (new)",
  "Every one of the 84 inputs listed with default, effect, and the Plutus recommendation."),
 ("N-6", "Indicator settings menu under the asset name (operator item 4)",
  "TradingView shows the indicator row under the symbol legend with a settings (gear) control. Find whether the Vela workbench has a study-legend API; if not, add a legend row in the pine-shell chart panel listing the script's inputs (PineTS exposes inputs) with edit → re-run.",
  "pine-ide/pine-ide/pine-ide.mjs + renderer tab (owner decided after the API read)",
  "Screenshot: a 'Plutus Vision v0' row under 'EURUSD · FIXTURE · 1h' with a gear; changing an input re-runs and the chart changes."),
 ("N-7", "D timeframe (operator: '15m up to the D')",
  "Fixture has no D cell. Options: aggregate 1H→D in pv-server.py (≈67 daily bars) or load real D bars. Decide with the operator's data source; never invent bars.",
  "scripts/pv-server.py + kernel TF map",
  "`pine-ide plutus-vision-v0.pine EUR/USD 1D` draws; vil.py adds the D case."),
 ("N-8", "Seal v2 after tuning", "Re-run vil.py + compare.py; regenerate canon; ship docs; checkpoint v2.", "Checkpoints/", "Self-contained launch from the v2 checkpoint."),
]
for nid, title, how, owner, acc in items:
    d += [f"## {nid} — {title}", "", f"- **How:** {how}", f"- **Owner file:** `{owner}`", f"- **Acceptance:** {acc}", ""]
d += ["## RISK REGISTER", "", "| risk | likelihood | impact | mitigation |", "|---|---|---|---|",
      "| tuning drifts into changing LuxAlgo logic | medium | high (F-06 repeat) | inputs only; compare.py parity must stay SMC 195/195 · POOLS 25/25 |",
      "| reader PASS hides visual deltas | high | high (T-03, T-07) | engineer read mandatory per TF |",
      "| raising the VOIDS cap squeezes SMC | high | medium | measure with compare.py after any cap change |",
      "| the dashboard session's ports get touched | low | high | launcher owns 9741/9754/9851/9222 only |",
      "| D bars fabricated from 1H look plausible but differ from broker daily candles | medium | medium | label the source; prefer real D data |",
      ""]
docs["NEXT_STEPS"] = d

# ───────────────────────────────── 4. TASK_QUEUE
d = HEAD("TASK QUEUE — PLUTUS VISION", "every task, its gate, its evidence, its status.")
d += ["| id | task | gate | evidence | status |", "|---|---|---|---|---|",
      "| T-01 | bundle the 4 LuxAlgo indicators into one | 1 `indicator()`; compiles | run title `Plutus Vision v0` | DONE |",
      "| T-02 | standalone Pine IDE (no dashboard coupling) | own ports; single mount | R-01 | DONE |",
      "| T-03 | per-source parity | compare.py | R-02 | DONE (VOIDS deviation documented) |",
      "| T-04 | one-command launcher | `pine-ide` exit 0 | R-01 | DONE |",
      "| T-05 | ViL ship gate | vil.py PASS + battery | R-03 | DONE |",
      "| T-06 | engineer read per TF | zero named deltas | R-04 | OPEN (3 deltas) |",
      "| T-07 | v1 checkpoint self-contained | launch from checkpoint | P-06 | AT SEAL |",
      "| T-08 | drawings non-interactable | drag test | — | OPEN (N-1) |",
      "| T-09 | VOIDS borderless | engineer read | — | OPEN (N-2) |",
      "| T-10 | label size / clipping | engineer read | — | OPEN (N-3) |",
      "| T-11 | sub-1H tuning via inputs | operator review | — | OPEN (N-4) |",
      "| T-12 | LuxAlgo settings map doc | 84 inputs covered | — | OPEN (N-5) |",
      "| T-13 | settings menu under the asset | screenshot + re-run | — | OPEN (N-6) |",
      "| T-14 | D timeframe | D render | — | OPEN (N-7) |",
      "| T-15 | v2 seal | full gate chain | — | OPEN (N-8) |",
      "", "## THE VERIFICATION MATRIX (what every tuning change must re-run)", "",
      "| pair \\ tf | 15m | 30m | 1H | 4H | D |", "|---|---|---|---|---|---|"]
for pair in ("EUR/USD", "GBP/USD", "DXY"):
    d.append(f"| {pair} | vil+read | vil+read | vil+read | vil+read | N-7 |")
d += ["", "Commands per cell: `bun scripts/pv-load.mjs plutus-vision-v0.pine <PAIR> <TF>` → `pine-ide --shot` → read →",
      "`python3 scripts/vil.py --pair <PAIR> --tfs <TF>`. Parity after any indicator edit: `python3 scripts/compare.py`.",
      "", "## GATE CHAIN (in order; a later gate never runs on a failed earlier one)", "",
      "1. compile — station `/run` success:true", "2. parity — compare.py SMC 195/195 · POOLS 25/25 · 0 not-in-baseline",
      "3. pipeline ViL — vil.py VIL GATE PASS", "4. engineer ViL — zero named deltas per TF", "5. docs — ship S1-S6, canon U1-U4",
      "6. checkpoint — self-contained launch", ""]
docs["TASK_QUEUE"] = d

# ───────────────────────────────── 5. BUILD_STATE
d = HEAD("BUILD STATE — PLUTUS VISION", "the sha chain, the module inventory, the frozen list.")
d += ["## SHA CHAIN", "",
      f"| artifact | sha256 |", "|---|---|",
      f"| plutus-vision-v0.pine (v1 baseline) | `{PSHA}` |",
      "| prior merged (pre-session, header-claimed zero deltas) | `d7e00609973165659b3cf7e2e1bd665a3cf1dcc986bf1bd1cd1a5d8b9d2e7b63` |",
      "| intermediate (after deguard + POOLS field fix) | `be14742298c1a249…` (16) |", ""]
d += ["## SOURCE SHAS (frozen — never edited)", "", "| source | sha256-16 | lines |", "|---|---|---|"]
for f in ("smart-money-concepts-smc", "liquidity-sweeps", "liquidity-voids-fvg", "buyside-sellside-liquidity"):
    p = SRC / f"{f}.pine"
    d.append(f"| {f}.pine | `{sha(p, 16)}` | {lines(p)} |" if p.exists() else f"| {f}.pine | ABSENT | — |")
d += ["", "## KEY-FILE INVENTORY", ""] + inv_rows(KEYFILES)
d += ["", "## ALL SCRIPTS", ""] + inv_rows(sorted(f"scripts/{p.name}" for p in (W / "scripts").iterdir() if p.is_file()))
d += ["", "## FROZEN LIST", "", "- the 4 LuxAlgo sources (luxalgo-smc/sources, sources/) — read-only reference",
      "- fixtures/bars/2026-07-06.json — byte-identical to PLUTUS/LIVE/agent/reference/fixtures/bars/2026-07-06.json",
      "- Checkpoints/v1-clean-baseline/ — sealed; changes go to the live tree + a new checkpoint", ""]
docs["BUILD_STATE"] = d

# ───────────────────────────────── 6. CHANGELOG
d = HEAD("CHANGELOG — PLUTUS VISION (append-only)", "the project history.")
d += ["## pre-2026-10-01 (prior sessions, from the session record)", "",
      "- LuxAlgo Library API: 806 indicators enumerated, 797 with source; SMC + 3 liquidity indicators chosen as the 4 cores.",
      "- PLUTUS_VISION_V0_BLUEPRINT.md (1057 lines); build package (DPL1_SPEC, WAVE_PLAN WAVES:4, MASTER_PROMPT).",
      "- W1 namespace (lexcheck.py), W2 merge, W3 budget allocator (later REMOVED), W4 behaviour diff.",
      "- Sandboxed pine-station on :9741 (sandbox_up.py); Pine IDE fork from the dashboard checkpoint.",
      "- Checkpoints: plutus-vision-v0-round-zero, plutus-vision-v0-station-verified.", "",
      "## 2026-10-01 — v1 CLEAN BASELINE", "",
      "- IDE: standalone pine.html (CSS links, no app.js, single mount, height chain); symlinks tabs/pine-ide + charts.",
      "- IDE: pv-server.py fixture feed; own rail :9754; Chrome kill hardening; relocatable launcher; `pine-ide` command.",
      "- Render: Pine labels → Vela text (vision.mjs:137); future bar_index anchors extrapolated (run.mjs:114).",
      "- Indicator: W3 guards removed (deguard.py); POOLS type field `x` restored; VOIDS bounded at 380 (voi_all).",
      "- Verification: compare.py parity; vil.py ViL ship gate replaces the code audit (operator order).",
      "- Docs: 6 ship docs + 11 canon docs created; checkpoint v1-clean-baseline sealed.", ""]
docs["CHANGELOG"] = d

# ───────────────────────────────── 7. COMPACTION_SURVIVAL
d = HEAD("COMPACTION SURVIVAL — PLUTUS VISION", "the resume point and the recovery commands if everything else is lost.")
d += ["## RESUME POINT", "", "Phase: TUNING (post-v1). Next action: N-1 (lock drawings) then N-2 (borderless VOIDS) — both in",
      "`pine-ide/pine-ide/vision.mjs`; re-run vil.py + engineer read on 15m/30m/1H/4H.", "",
      "## RECOVERY COMMANDS", "", "```",
      "pine-ide                                  # bring the rig back (fails loudly with a named code if it cannot)",
      "ss -ltnp | grep -E ':(9741|9754|9851|9222)'   # who owns the ports",
      "tail -20 /tmp/pv-station.log /tmp/pv-vil-rail.log /tmp/pv-ide-http.log",
      "python3 scripts/vil.py && python3 scripts/compare.py",
      "python3 scripts/gen_canon.py              # regenerate these docs from disk",
      "```", "",
      "## NAMED FAILURE CODES (pv-ide.sh / pv-load.mjs) → ACTION", "",
      "| code | meaning | action |", "|---|---|---|",
      "| DISPLAY_DOWN | X display :3 absent | bring up the agent display (computer-use-virtual-display skill) |",
      "| FIXTURE_ABSENT | <tree>/fixtures missing | copy the fixture (BUILD_STATE frozen list) |",
      "| ENGINE_ABSENT | PineTS not installed | `npm install` in pine-ide/pine-station |",
      "| PORT_HELD | a port survived fuser -k | find the supervisor (`hub ps`) and stop it |",
      "| STATION_DOWN / RAIL_DOWN / SERVER_DOWN | process failed to bind | read its /tmp/pv-*.log |",
      "| CHROME_STUCK | a Chrome main survived kill -9 | inspect ps state; reboot the display |",
      "| NO_PAGE | no pine.html target on CDP :9222 | Chrome failed to start — /tmp/pv-ide-chrome.log |",
      "| NO_HANDLE | window.PlutusPineShell absent | mount failed — browser console via CDP |",
      "| RUN_FAILED | station rejected the script | read the code/detail; compile error in the Pine |",
      "| DOUBLE_MOUNT | >1 .pine-shell | a manual mount() came back into pine.html |",
      "| NOTHING_DRAWN | run ok, 0 drawings | indicator drew nothing — planted-defect class |", ""]
docs["COMPACTION_SURVIVAL"] = d

# ───────────────────────────────── 8. EVIDENCE_STATE
d = HEAD("EVIDENCE STATE — PLUTUS VISION", "per-gate evidence with shas; the honest gaps.")
d += ["## GATE 2 — PARITY (scripts/compare.py → COMPARE.json)", ""]
if CMP:
    d += ["| subsystem | source ok | counts |", "|---|---|---|"]
    d += [f"| {n} | {v.get('ok')} | `{json.dumps(v.get('counts'))[:110]}` |" for n, v in CMP.get("sources", {}).items()]
    d += [f"| MERGED | — | `{json.dumps(CMP.get('merged'))[:110]}` |", "",
          f"lost={CMP.get('lost')} extra={CMP.get('extra')} — explained in SPEC_VIOLATION_LOG (VOIDS cap 120 + SWEEPS-raw 1; extra = 258 SWEEPS drawings).", ""]
d += ["## GATE 3 — PIPELINE ViL (scripts/vil.py → vil/vil-results.json)", "",
      f"runId `{VIL.get('runId')}` · overall **{VIL.get('overallVerdict')}** · indicator `{str(VIL.get('indicatorSha256'))[:16]}`", "",
      "| case | design | verdict | png sha256-16 | bytes | pixelStd | reader | why |", "|---|---|---|---|---|---|---|---|"]
for c in VIL.get("scenarios", []):
    e = c.get("extraction", {}) or {}
    r = (c.get("reader") or {}).get("reader") or "—"
    d.append(f"| {c['id']} | {c['design']} | {c['verdict']} | `{str(e.get('sha256', '—'))[:16]}` | {e.get('bytes', '—')} | "
             f"{e.get('pixelStd', '—')} | {pathlib.Path(r).name if r != '—' else '—'} | {str(c.get('why'))[:60]} |")
d += ["", "## GATE 4 — ENGINEER ViL", "", "FAIL — 3 named deltas (TESTING_LOG R-04): D1 VOIDS tan borders (PIPELINE) · D2 label overlap ·",
      "D3 right-edge W/S clipping. Recorded against the GATE-3 shas above.", "",
      "## HONEST GAPS", "",
      "- VOIDS 380/500 by design (engine ceiling).", "- 3-4 dropped anchors = SMC source behaviour.",
      "- No D timeframe evidence (no D data).", "- Drawings draggable; no settings menu.",
      "- The reader is a 4B model: it confirmed presence, it did not catch D1-D3 (T-07).", ""]
docs["EVIDENCE_STATE"] = d

# ───────────────────────────────── 9. DECISION_CHAIN
d = HEAD("DECISION CHAIN — PLUTUS VISION", "the operator's rulings VERBATIM and the decisions derived from them.")
d += ["## OPERATOR RULINGS (verbatim, newest last)", ""]
rulings = [
 "take the working 4 lux algo indicators, bundle them into ONE indicator, and render it on the pine IDE chart so i can see everything and MAKE SURE IT IS PROPERLY FUCKING DONE",
 "no fucking reinventing or customizing anything",
 "Assemble production grade components > build from scratch",
 "/home/leviathan/JARVIS_WORKSPACE/Shared_Workspace/PLUTUS_VISION - THIS IS YOUR NEW WORKSPACE. MIGRATE ALL *YOUR* PROJECT FILES TO HERE FULLY",
 "THIS IS REFERENCE ONLY FOR YOU TO FORK THE PINE IDE TAB INTO A STANDALONE PINE IDE FOR THIS PROJECT'S TESTING SO YOU DONT INTERFERE WITH THE DHA OTHER SESSIONS WORK",
 "YOU WILL DO PROPER VISION IN THE LOOP VERIFICATION TO MAKE SURE IT WORKS",
 "if i cannot see it - its not real",
 "Take the simplest path, don't overthink or over engineer anything.",
 "Create a clean, simple, separate launcher where I can just type Pine E IDE in the terminal and launch this exact standalone fucking shell",
 "save this checkpoint in the plutus vision folder as v1 clean baseline ... make sure there is a checkpoint for the indicator itself + the entire pine shell ide ... self contianed within the checkpoint",
 "the indicator should not be interactable right now ... indicators are not interactable they just render. that is the normal behavior on trading view",
 "REPLACE QWEN CODE AUDIT WITH VISION IN THE LOOP /home/leviathan/JARVIS_WORKSPACE/Shared_Workspace/Bibles/VISION_IN_THE_LOOP_ENGINEERING_BIBLE.md",
]
d += [f"{i + 1}. \"{r}\"" for i, r in enumerate(rulings)]
d += ["", "## DECISIONS", "", "| id | decision | from ruling | reason / evidence |", "|---|---|---|---|",
      "| D-01 | standalone pine.html host without app.js | 5 | app.js re-render fight (EN-002) |",
      "| D-02 | own ports 9741/9754/9851, never the dashboard's | 5 | EN-016 |",
      "| D-03 | remove every W3 budget guard | 2 | guards changed output (EN-012, F-06) |",
      "| D-04 | bound only VOIDS (380) under the shared 500-box ceiling | 1, 2 | bisection: VOIDS GCs SMC's bar-0 boxes (EN-013) |",
      "| D-05 | Pine label → Vela text | 1, 7 | pricelabel prints price (EN-014) |",
      "| D-06 | ViL gate (vil.py) is the ship gate; code audit retired here | 12 | F-05 |",
      "| D-07 | sub-1H tuning by INPUT values, not logic edits | 2, 11 | keeps LuxAlgo behaviour verbatim |",
      "| D-08 | checkpoint = full self-contained tree incl. node_modules + fixture | 10 | P-06 |",
      "| D-09 | launcher relocatable via PINE_IDE_HOME | 9, 10 | EN-020 |", ""]
docs["DECISION_CHAIN"] = d

# ───────────────────────────────── 10/11. RUNNING LOGS
d = HEAD("RUNNING BUILD LOG — PLUTUS VISION (append-only, high frequency)", "timestamped build steps.")
d += ["| when (2026-10-01 UTC) | step | result |", "|---|---|---|",
      "| ~15:30 | index.html CSS links + dashboardConfig | styled after cache wipe |",
      "| ~15:35 | standalone pine.html, tabs/pine-ide + charts symlinks | mount ok, workbench loads |",
      "| ~15:40 | pv-server.py bars feed | 1603 bars EUR/USD 1H |",
      "| ~15:45 | height chain | host 861×719, chart visible |",
      "| ~15:50 | remove manual mount | shells:1 |",
      "| ~15:52 | pine-ide command + pv-load.mjs | exit 0 JSON line |",
      "| ~15:53 | compare.py parity | POOLS 0/25 found |",
      "| ~15:54 | deguard.py | guards 0 |",
      "| ~15:55 | POOLS field fix, VOIDS voi_all 380 | SMC 195/195 POOLS 25/25 |",
      "| ~15:56 | vision.mjs labels → text; run.mjs anchor extrapolation | BOS/CHoCH text visible |",
      "| ~15:58 | own rail :9754 | reader PASS |",
      "| ~16:10 | relocatable launcher, fixture in tree, setsid -f, PORT_HELD | cold 9.1 s |",
      "| ~16:17 | vil.py ViL gate | VIL GATE PASS (4 TFs + battery) |",
      "| ~16:30 | ship docs + canon docs | written |",
      "| seal | checkpoint v1-clean-baseline | see CHECKPOINT_MANIFEST |", ""]
docs["RUNNING_BUILD_LOG"] = d
d = HEAD("RUNNING DEBUG LOG — PLUTUS VISION (append-only, high frequency)", "timestamped symptom → cause pairs; full entries in DEBUG_LOG.md.")
d += ["| when (2026-10-01 UTC) | symptom | cause | DEBUG_LOG |", "|---|---|---|---|",
      "| ~15:30 | left panel unstyled | tab CSS via file:// fetch path | EN-001 |",
      "| ~15:33 | host lost the tab loop | app.js re-render | EN-002 |",
      "| ~15:35 | kernel 404 | symlink missing / wrong depth | EN-003 |",
      "| ~15:37 | WORKBENCH_ABSENT | charts/ not served | EN-004 |",
      "| ~15:40 | FEED_BAD_REPLY 404 | no bars API | EN-005 |",
      "| ~15:44 | blank chart | canvas 24,677 px | EN-006 |",
      "| ~15:46 | prefill ran | setValue absent | EN-007 |",
      "| ~15:47 | 0 bars | '1h' lowercase | EN-008 |",
      "| ~15:49 | two editors | double mount | EN-009 |",
      "| ~15:55 | stale labels after edit | Chrome survivors | EN-010 |",
      "| ~15:53 | POOLS 0/25 | renamed type field | EN-011 |",
      "| ~15:54 | deltas from guards | W3 allocator | EN-012 |",
      "| ~15:55 | SMC 190/195, then VOIDS 0/465 | 500-box GC; decl inside if | EN-013 |",
      "| ~15:56 | labels show prices | Vela pricelabel | EN-014 |",
      "| ~15:57 | anchors dropped | future bar_index | EN-015 |",
      "| ~15:58 | rows to :9444 | inherited rail constant | EN-016 |",
      "| ~15:53 | None parity keys | wrong schema | EN-017 |",
      "| ~15:54 | circular import | bisect.py name | EN-018 |",
      "| ~16:05 | launcher hang | hub-supervised server + child wait | EN-019 |",
      "| ~16:08 | not relocatable | hardcoded paths | EN-020 |",
      "| ~16:18 | tan striped VOIDS | brass default border | EN-021 (OPEN) |", ""]
docs["RUNNING_DEBUG_LOG"] = d

# ── THE SHA BLOCK — injected into the 5 READ-FIRST docs, verbatim and identical ─────────────
# The pin's canon gate: "the 5 read-first docs agree on the SHA". Hand-carrying it let it go
# stale (the last hand block read D1 b6dda2dae441 while D1 had long moved). It is GENERATED
# now, so every regen re-stamps all five from the same disk read.
READ_FIRST = ("POST-COMPACTION_PROMPT", "CURRENT_STATE", "BUILD_STATE", "EVIDENCE_STATE", "NEXT_STEPS")
SHA_FILES = ["lqz-luxalgo.pine", "lqz-plutus.pine", "plutus-vision-v1.pine", "plutus-vision-v0.pine"]
sha_block = ["", "## THE SHA BLOCK (all read-first docs carry this verbatim)", "",
             "| artifact | sha256[:16] |", "|---|---|"]
for _f in SHA_FILES:
    _p = W / _f
    sha_block.append(f"| {_f} | `{sha(_p, 16)}` |" if _p.exists() else f"| {_f} | ABSENT |")
sha_block.append("")
for _n in READ_FIRST:
    docs[_n] = list(docs[_n]) + sha_block

# ── THE WRITE — APPEND-SAFE, HAND-SECTION PRESERVING ────────────────────────────
# MEASURED 2026-10-02: this loop used to `write_text` UNCONDITIONALLY, so a regen clobbered
# the "append-only" docs outright -- RUNNING_BUILD_LOG fell 255 → 23 lines, RUNNING_DEBUG_LOG
# 214 → 29, 642 lines across 12 files. The docs' own titles said "append-only" and the code
# disagreed with them. THE CONTRACT NOW, in code:
#   · the APPEND docs keep their entire history below a marker; the generated head refreshes.
#   · the OVERWRITE docs keep every hand-written section between CANON-HAND markers; the
#     generated inventory refreshes around it. (The manifest already carried a marker
#     convention -- <!-- LQZ-SHA-BLOCK --> -- this generalises it.)
APPEND_DOCS = {"CHANGELOG", "RUNNING_BUILD_LOG", "RUNNING_DEBUG_LOG"}
APPEND_MARK = "<!-- LQZ:APPEND-BELOW -->"
HAND_OPEN, HAND_CLOSE = "<!-- LQZ:CANON-HAND -->", "<!-- /LQZ:CANON-HAND -->"


def preserved_hand(text):
    """every CANON-HAND block in `text`, in order."""
    out, i = [], 0
    while True:
        a = text.find(HAND_OPEN, i)
        if a < 0:
            break
        b = text.find(HAND_CLOSE, a)
        if b < 0:
            break
        out.append(text[a:b + len(HAND_CLOSE)])
        i = b + len(HAND_CLOSE)
    return out


for name, body in docs.items():
    p = C / f"{name}.md"
    gen = "\n".join(body) + "\n"
    if p.exists():
        old = p.read_text()
        if name in APPEND_DOCS:
            hist = old.split(APPEND_MARK, 1)[1] if APPEND_MARK in old else old
            gen = gen + "\n" + APPEND_MARK + "\n" + hist
        else:
            hand = preserved_hand(old)
            if hand:
                gen = gen + "\n\n" + "\n\n".join(hand) + "\n"
    p.write_text(gen)
    print(f"{name:24} {gen.count(chr(10)):4} lines")
(C / "CANON_MANIFEST.md").write_text("\n".join(
    ["# CANON MANIFEST — PLUTUS VISION", f"Generated: {NOW}", f"Indicator sha256: {PSHA}",
     "Generator: scripts/gen_canon.py (re-run after every milestone)", "Docs:"] +
    [f"- {n}.md ({len(b)} lines) — {'append' if n in ('CHANGELOG', 'RUNNING_BUILD_LOG', 'RUNNING_DEBUG_LOG') else 'overwrite'}" for n, b in docs.items()]) + "\n")
